feat: add copy topic qustions in user question
vkarelina/q-stats__backend pull request #10
Opened 2024-11-07 12:02 UTC by vkarelina

Added:
- Add to copy topic questions in user question
- Add to create answer null for other questions
- Add to create answer null for custom questions

2024-11-07 12:39 UTC, ysimakina commented on src/answers/answers.service.ts
> +      });
issue: дублирование кода, можно вынести в отдельную функцию

2024-11-07 14:18 UTC, skubedin requested changes

2024-11-07 14:18 UTC, skubedin commented on src/users/users.service.ts
> +    return this.userRepository.findAll({ attributes: ['id', 'name'] });
**suggestion:** Передавай поля в аргументах, там же можно указывать условия выборки и т д

2024-11-07 14:18 UTC, skubedin commented on src/user-questions/user-questions.service.ts
> +
**typo:** Пустая строка избыточна. Он не ничего не разделяет

2024-11-07 14:18 UTC, skubedin commented on src/user-questions/copy-topic-question.service.ts
> +      where: { userId, topicQuestionId: topicQuestions.map((question) => question.id) },
**question:** Может просто по topicId смотреть?

2024-11-07 14:18 UTC, skubedin commented on src/user-questions/copy-topic-question.service.ts
> +    this.userQuestionRepository.bulkCreate(userQuestionsData);
**issue:** Ты не дожидаешься выполнения. Если будет ошибка, клиент об этом не узнает.

Если есть большое количество (больше одного) запросов с изменением в БД, то стоит использовать транзакции.

2024-11-11 14:05 UTC, s-skubedin approved these changes

2024-11-11 14:05 UTC, s-skubedin commented on src/users/users.service.ts
> +    order: Order = [],
**suggestion:** Можешь передавать объект, и напрямую прокидывать в findAll. Типизировать также можешь типом из sequelize.

2024-11-11 14:05 UTC, s-skubedin commented on src/user-questions/user-questions.service.ts
> +    const transaction = await this.sequelize.transaction();
**note:** Однажды делал реализацию транзакции через декоратор, удобно. Можешь как-нибудь попробовать реализовать, на Medium есть пример

2024-11-11 14:05 UTC, s-skubedin commented on src/topic-questions/topic-questions.service.ts
> +    ],
**note:** Думаю, есть тип с генериком

2024-11-11 14:12 UTC, ysimakina approved these changes

2024-11-12 13:54 UTC, merged