feat: create module answer
vkarelina/q-stats__backend pull request #9
Opened 2024-11-05 15:04 UTC by vkarelina

Added:
- Create module answer
- Create or update answer
- Get answers
- Get answers for questions

2024-11-06 06:42 UTC, ysimakina commented on src/user-questions/user-questions.controller.ts
> +    console.log(1111)
**chore:** лишний console.log

2024-11-06 07:07 UTC, s-skubedin requested changes

2024-11-06 07:07 UTC, s-skubedin commented on src/answers/entities/answer.entity.ts
> +import { UserQuestion } from 'src/user-questions/entities/user-question.entity';
**suggestion:** Используй одну стилистику импортов. Во всем проекте импорт относительный

2024-11-07 07:32 UTC, s-skubedin approved these changes

2024-11-07 07:53 UTC, ysimakina approved these changes

2024-11-07 07:59 UTC, merged